#!/usr/bin/env python3
"""
GERADOR DE ÍCONES PARA AURORA MULHER SEGURA
Execute: python generate_icons.py
"""

import base64
from pathlib import Path
import os

# Cria diretório se não existir
icons_dir = Path("static/icons")
icons_dir.mkdir(parents=True, exist_ok=True)

# ================================
# 1. aurora-192.png
# ================================
aurora_192_base64 = """
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA
AXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAQ9SURBVHgB7d1BahVJEIDhquMCQvYM8hQeZwQ9
wgQcQRCEEQRBcCaC4MUIgtcRPFkzM43MfK8qM5Mpquv7fsi8UBl4n6+6uvq+fPv+/wFgN/8kAHYC
AIAFAAAsAABgAQAAm37+/P6fg92/vH32/PX7/w92//L22fP5t+8+2P3L22fP59+++/fvP2/mH//y
9tnz+bfv/ufPX/8EAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwA
""".strip().replace("\n", "")

with open(icons_dir / "aurora-192.png", "wb") as f:
    f.write(base64.b64decode(aurora_192_base64))
print("? Criado: aurora-192.png")

# ================================
# 2. aurora-512.png
# ================================
aurora_512_base64 = """
iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAYAAAD0eNT6AAAACXBIWXMAAAsTAAALEwEAmpwYAAAA
AXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAVnSURBVHgB7d1BchVHEoDRqnsDsXsGeQqPM4Ie
YQKOIAjCCIIgOBNB8GIEwesInqyZmUZm/ldV3wfMy/t+YL5+vaur7358+/7/AWBX/yYA9gIAgAUA
ACwAAGABAAALAAAsAABgAQCA1v78+f0/B7t/efvs+ev3/x/s/uXts+fzb999sPuXt8+ez7999+/f
f97MP/7l7bPn82/f/c+fv/4JANgJAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACA
BQAALAAAYAEAAAsAAA0AAFgAAMACAAAWAACwAIC9/AdZRltdtAmc9wAAAABJRU5ErkJggg==
""".strip().replace("\n", "")

with open(icons_dir / "aurora-512.png", "wb") as f:
    f.write(base64.b64decode(aurora_512_base64))
print("? Criado: aurora-512.png")

# ================================
# 3. aurora-192-maskable.png
# ================================
# Para ícone maskable, vamos criar um SVG simples que pode ser convertido
maskable_svg = '''<?xml version="1.0" encoding="UTF-8"?>
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="192" height="192" rx="48" fill="#FF2D55"/>
    <path d="M96 56C74.4 56 56 74.4 56 96C56 117.6 74.4 136 96 136C117.6 136 136 117.6 136 96C136 74.4 117.6 56 96 56ZM96 128C78.4 128 64 113.6 64 96C64 78.4 78.4 64 96 64C113.6 64 128 78.4 128 96C128 113.6 113.6 128 96 128Z" fill="white"/>
    <circle cx="96" cy="96" r="32" fill="white"/>
</svg>'''

with open(icons_dir / "aurora-192-maskable.png", "w") as f:
    f.write(maskable_svg)
print("? Criado: aurora-192-maskable.png (SVG)")

# ================================
# 4. aurora-512-maskable.png
# ================================
maskable_svg_large = '''<?xml version="1.0" encoding="UTF-8"?>
<svg width="512" height="512" viewBox="0 0 512 512" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="512" height="512" rx="128" fill="#FF2D55"/>
    <path d="M256 128C192 128 128 192 128 256C128 320 192 384 256 384C320 384 384 320 384 256C384 192 320 128 256 128ZM256 352C211.2 352 176 316.8 176 272C176 227.2 211.2 192 256 192C300.8 192 336 227.2 336 272C336 316.8 300.8 352 256 352Z" fill="white"/>
    <circle cx="256" cy="256" r="96" fill="white"/>
</svg>'''

with open(icons_dir / "aurora-512-maskable.png", "w") as f:
    f.write(maskable_svg_large)
print("? Criado: aurora-512-maskable.png (SVG)")

# ================================
# 5. sos-192.png
# ================================
sos_base64 = """
iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAYAAABS3GwHAAAACXBIWXMAAAsTAAALEwEAmpwYAAAA
AXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAO8SURBVHgB7d1BahVLEIDhquMCQvYM8hQeZwQ9
wgQcQRCEEQRBcCaC4MUIgtcRPFkzM43MfK8qM5Mpquv7fsi8UBl4n6+6uvq+fPv+/wFgN/8kAHYC
AIAFAAAsAABgAQAAm37+/P6fg92/vH32/PX7/w92//L22fP5t+8+2P3L22fP59+++/fvP2/mH//y
9tnz+bfv/ufPX/8EAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwAACABQAALAAA
YAEAoAEAAAsAAFgAAMACAAAWAACwAACABQAALAAAYAEAAAsAAFgAAMACAAAWAACwA
""".strip().replace("\n", "")

with open(icons_dir / "sos-192.png", "wb") as f:
    f.write(base64.b64decode(sos_base64))
print("? Criado: sos-192.png")

# ================================
# 6. badge.png (para notificações)
# ================================
badge_svg = '''<?xml version="1.0" encoding="UTF-8"?>
<svg width="192" height="192" viewBox="0 0 192 192" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="96" cy="96" r="96" fill="#FF2D55"/>
    <circle cx="96" cy="96" r="80" fill="white"/>
    <text x="96" y="115" text-anchor="middle" font-family="Arial, sans-serif" font-size="72" font-weight="bold" fill="#FF2D55">!</text>
</svg>'''

with open(icons_dir / "badge.png", "w") as f:
    f.write(badge_svg)
print("? Criado: badge.png (SVG)")

# ================================
# 7. Screenshots (placeholders)
# ================================
screenshots_dir = Path("static/screenshots")
screenshots_dir.mkdir(parents=True, exist_ok=True)

# Phone screenshot
phone_svg = '''<?xml version="1.0" encoding="UTF-8"?>
<svg width="1080" height="1920" viewBox="0 0 1080 1920" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="1080" height="1920" fill="#050510"/>
    <rect x="40" y="40" width="1000" height="1840" rx="40" fill="#16002B"/>
    <rect x="80" y="80" width="920" height="360" rx="20" fill="#FF2D55"/>
    <rect x="80" y="480" width="920" height="120" rx="10" fill="#2D3748"/>
    <rect x="80" y="640" width="920" height="400" rx="20" fill="#2D3748"/>
    <circle cx="540" cy="1200" r="200" fill="#FF2D55"/>
    <text x="540" y="1220" text-anchor="middle" font-family="Arial" font-size="80" font-weight="bold" fill="white">SOS</text>
</svg>'''

with open(screenshots_dir / "phone.png", "w") as f:
    f.write(phone_svg)
print("? Criado: screenshots/phone.png (SVG placeholder)")

# Tablet screenshot
tablet_svg = '''<?xml version="1.0" encoding="UTF-8"?>
<svg width="1920" height="1080" viewBox="0 0 1920 1080" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="1920" height="1080" fill="#050510"/>
    <rect x="60" y="60" width="1800" height="960" rx="40" fill="#16002B"/>
    <rect x="120" y="120" width="1680" height="200" rx="20" fill="#FF2D55"/>
    <rect x="120" y="380" width="1680" height="80" rx="10" fill="#2D3748"/>
    <rect x="120" y="500" width="1680" height="400" rx="20" fill="#2D3748"/>
    <circle cx="960" cy="900" r="150" fill="#FF2D55"/>
    <text x="960" y="920" text-anchor="middle" font-family="Arial" font-size="60" font-weight="bold" fill="white">SOS</text>
</svg>'''

with open(screenshots_dir / "tablet.png", "w") as f:
    f.write(tablet_svg)
print("? Criado: screenshots/tablet.png (SVG placeholder)")

# ================================
# 8. sirene.mp3 (placeholder - arquivo vazio)
# ================================
audio_dir = Path("static/audio")
audio_dir.mkdir(parents=True, exist_ok=True)

# Crie um arquivo de áudio placeholder
with open(audio_dir / "sirene.mp3", "wb") as f:
    # Escreva alguns bytes (arquivo MP3 vazio/inválido, apenas para placeholder)
    f.write(b'MP3 placeholder - substitua por um arquivo real de sirene')
print("? Criado: audio/sirene.mp3 (placeholder - substitua com arquivo real)")

print("\n" + "="*50)
print("? TODOS OS ARQUIVOS CRIADOS COM SUCESSO!")
print("="*50)
print("\n??  IMPORTANTE:")
print("   1. Os arquivos .png com SVG são placeholders")
print("   2. Para produção, substitua por imagens reais")
print("   3. Baixe um som de sirene real para sirene.mp3")
print("\n?? Estrutura criada:")
for root, dirs, files in os.walk("static"):
    level = root.replace("static", "").count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 4 * (level + 1)
    for file in files:
        print(f"{subindent}{file}")